version: '3.9'

services:
  db:
    build: ./psql
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  scraper:
    build: .
    stdin_open: true
    tty: true

volumes:
  postgres-data:
